### ISSUE TITLE
Find a better way to display game tabs.

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/Arduino-Source#173]
Tabs are overflowing in default mode. Looks fine in dark mode.

Default mode has a lot of padding next the text which I don't know how to adjust.

![image](https://user-images.githubusercontent.com/4991305/188092058-b0ae698a-c1ee-43f2-beb8-2af563a7dbfc.png)

**Comment by pifopi** [comment]
Would something like this work ? https://doc.qt.io/qt-6/qtwidgets-mainwindows-menus-example.html

**Comment by Mysticial** [comment]
You want a menu dropdown? Or a `QComboBox`?

**Comment by Mysticial** [comment]
https://github.com/PokemonAutomation/Arduino-Source/commit/d225e6e7453c3c6d38bbc18fd0e7c08b11c44030
