### ISSUE TITLE
Game pad controls.

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/Arduino-Source#25]
pif started working on this, but the implementation isn't prod-ready. We will need a new UI drop-down menu to select the game pad and figure out the race condition on reading game pad state.

**Comment by pifopi** [comment]
https://github.com/pifopi/Arduino-Source-Internal/tree/gamepad
If someone want to take a look at those snipset.
https://discord.com/channels/695809740428673034/722200321916534876/883425899909886002
for a discussion about it

**Comment by pifopi** [comment]
Gamepad support was dropped with qt6 :(
