### ISSUE TITLE
Sleepy randomly fails to start.

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/Arduino-Source#34]
Part of: https://github.com/PokemonAutomation/Arduino-Source/issues/28

Sometimes clicking the start button fails to properly start the bot. All commands are unrecognized.

**Comment by Koi-3088** [comment]
Should be. Commands are now initialized alongside settings, before attempting to connect the Discord client. It used to be tied to the `onReady()` event but it can sometimes not get fired due to yet unknown reasons (which is why it would sometimes not initialize commands).
